### ISSUE TITLE
AxisOrder support for ImageJ1 ordering

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-vistools#14]
@tpietzsch 

The default AxisOrder in ImageJ1 is XYCZT. 
Would it be possible to also have this as one option in the BDV?
Currently this is not available:
https://github.com/bigdataviewer/bigdataviewer-vistools/blob/master/src/main/java/bdv/util/AxisOrder.java#L17

**Comment by imagejan** [comment]
@tischi so you mean `XYCZT ( 5, 2, true, false )` is missing?

**Comment by tpietzsch** [comment]
Actually I think it would be `XYCZT(5,2,false,false)`. See comments here https://github.com/bigdataviewer/bigdataviewer-vistools/blob/38c36a2f97466d0d1e35431f4c583d02842fb6ae/src/main/java/bdv/util/AxisOrder.java#L110-L125 for meaning of the boolean parameters.
If you want to try it out and create a PR that would be great
