### ISSUE TITLE
adjust brightness

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-vistools#2]
fantastic tool! is there a way to adjust the brightness?

**Comment by tpietzsch** [comment]
Yes.
https://github.com/bigdataviewer/bigdataviewer-vistools/blob/master/src/main/java/bdv/util/BdvSource.java#L22-L24
(`BdvSource` is what you get when you show/add an image via `BdvFunctions.show`)

**Comment by tischi** [comment]
excellent! works!
