### ISSUE TITLE
request for another example

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-vistools#22]
Hello, 

@tpietzsch 

If possible, I would like to ask for one more example.

In below code you show how to modify the keyboard responses, but, as I understand it, this links to already defined behavior, somehow encoded in strings such as "2d drag translate". 

Would it be possible to add a simple example, where, e.g., the user types 'p' and then there is a newly defined function triggered that retrieves the current x,y,z coordinates of the mouse in the data set? 

https://github.com/bigdataviewer/bigdataviewer-vistools/blob/master/src/test/java/bdv/util/InputConfigExample.java#L27

**Comment by tpietzsch** [comment]
I added two new examples:
https://github.com/bigdataviewer/bigdataviewer-vistools/commit/957e017fcc13b22eb937d42f864faf838dabd512
