### ISSUE TITLE
Changing display range programmatically

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-vistools#33]
Hi @tibuch @tpietzsch (@metavibor),

I can change the display settings like this:

```
bdvStackSource.getBdvHandle().getSetupAssignments().getConverterSetups().get(channel).setDisplayRange( min, max );
```

This works in terms of changing the display of the source, however it does not seem to notify the Bdv user interface. The next time one goes to the menu to change the Brightness Settings, there are other values... Am I missing something?

**Comment by tpietzsch** [comment]
@tischi yes, I think you are missing this: https://github.com/bigdataviewer/bigdataviewer-vistools/blob/0c27a1db87fcb02898e8f2934ac988d00514bff1/src/main/java/bdv/util/BdvSource.java#L22
