### ISSUE TITLE
Make a new release so a vistools release is available that is compatible with the latest imglib2-cache release

### ISSUE THREAD

**Issue by hanslovsky** [bigdataviewer/bigdataviewer-vistools#34]
In the current release of vistools ([1.0.0-beta-17](https://github.com/bigdataviewer/bigdataviewer-vistools/releases/tag/bigdataviewer-vistools-1.0.0-beta-17)) , the `SharedQueue` constructor does not work with the latest release of [imglib2-cache](https://github.com/imglib/imglib2-cache) ([1.0.0-beta-12](https://github.com/imglib/imglib2-cache/releases/tag/imglib2-cache-1.0.0-beta-12)) because the super constructor has changed. a5d2ca9f0f4f654c7a21371b2e0b0ebb1bb4cb1f fixes this but is not available in a release version, yet. @tpietzsch can you cut a release?

Thanks

**Comment by tpietzsch** [comment]
@hanslovsky I'm releasing 1.0.0-beta-18 now

**Comment by hanslovsky** [comment]
Thanks a lot!!!
