### ISSUE TITLE
Making addSource(handle, source, numTimepoints) method public

### ISSUE THREAD

**Issue by NicoKiaru** [bigdataviewer/bigdataviewer-vistools#36]
Right now I don't see how to add a Source with a number of Timepoints using `BdvFunctions`

Can we make the following method public ? That should solve it I guess.

https://github.com/bigdataviewer/bigdataviewer-vistools/blob/1322f4c6c9ba6f35353c90ea1954cd43b156854b/src/main/java/bdv/util/BdvFunctions.java#L567

**Comment by tischi** [comment]
I don't know. I usually just use 
```BdvFunctions.show( source, numTimePoints, BdvOptions.options().addTo( bdvHandle ) )```
Is that not sufficient for your use case?

**Comment by NicoKiaru** [comment]
Missed it! Thanks @tischi. Closing.
