### ISSUE TITLE
Update to bdv-core 9.0.6 to solve list : no such field exception

### ISSUE THREAD

**Issue by NicoKiaru** [bigdataviewer/bigdataviewer-vistools#46]
When adding an overlay to Bdv, I get an error similar to https://github.com/bigdataviewer/bigdataviewer-core/pull/103, maybe due to the same incompatibility of listeners raised by @imagejan  (https://github.com/bigdataviewer/bigdataviewer-vistools/blob/f1bbdc498210d46062808bf8f3e0655aa4431215/src/main/java/bdv/util/PlaceHolderOverlayInfo.java#L13)

This happens only if an overlay is present in bdv. Regular sources are fine.

Updating bdv-core version to 9.0.6 in this repo solves the issue - could this be updated and relased to maven scijava (1.0.0-beta-21-SNAPSHOT) @tpietzsch ?

**Comment by tpietzsch** [comment]
@NicoKiaru Thanks for pointing that out! I bumped the parent to pom-scijava 29.2.1, which should solve the issue as well. I'm releasing 1.0.0-beta-21 now
