### ISSUE TITLE
NPE on bdvhandleframe.getViewerPanel().getSplitPanel() + access to location of the division

### ISSUE THREAD

**Issue by NicoKiaru** [bigdataviewer/bigdataviewer-vistools#49]
In this line : 

https://github.com/bigdataviewer/bigdataviewer-vistools/blob/6bc8d2f00a6644ecbb0a9ad9599dd51a9bc53a1b/src/main/java/bdv/util/BdvHandleFrame.java#L121

The splitPanel field is not initialized.

Also, the setDividerSize method can be accessed, but it's not so useful because it just changes the size of the gap between the image and the sidepanel. As far as I understand, an access to the method `setLocation(x,y)` could be more useful, even if omitting the y argument `setSplitPanelDivisionLocation(y)` could be even more convenient.

I can make a PR if you wish

**Comment by tpietzsch** [comment]
> The splitPanel field is not initialized.

Oops... Yes, a PR would be very welcome!

> Also, the setDividerSize method can be accessed, but it's not so useful because it just changes the size of the gap between the image and the sidepanel. As far as I understand, an access to the method `setLocation(x,y)` could be more useful, even if omitting the y argument `setSplitPanelDivisionLocation(y)` could be even more convenient.

I don't really get it. Could you explain what you want to do? There is `SplitPanel.setDividerLocation(int)` (inherited from JSplitPanel) and `SplitPanel.setCollapsed(boolean)`.

**Comment by NicoKiaru** [comment]
Here you go for the PR :

https://github.com/bigdataviewer/bigdataviewer-vistools/pull/50

And my mistake for the `setDividerLocation` : I only looked at the methods in `SplitPanel` and not at the ones inherited from `JSplitPanel`. Everything was there and accessible.

**Comment by NicoKiaru** [comment]
Done in the merged PR above
