### ISSUE TITLE
bdv.utils.VolatileSource conflicts with playground

### ISSUE THREAD

**Issue by mkitti** [bigdataviewer/bigdataviewer-vistools#62]
There is another `bdv.utils.VolatileSource` in bigdataviewer-playground:

https://github.com/bigdataviewer/bigdataviewer-playground/blob/05c48eef7fa724e32bc595ea8949c206cdbe2333/src%2Fmain%2Fjava%2Fbdv%2Futil%2FVolatileSource.java#L88

**Comment by tpietzsch** [comment]
Argh. We should really adopt naming packages after artefacts. `bdv.util` should be `org.bigdataviewer.vistools` for bigdataviewer-vistools. And `org.bigdataviewer.playground` for bigdataviewer-playground.

**Comment by tpietzsch** [comment]
@axtimwalde @NicoKiaru Can you estimate how widely used your respective versions of `VolatileSource` are? Can we still just rename one of them?

**Comment by NicoKiaru** [comment]
I'll rename mine, it's used only internally and is not in any of the persisted json files around.

If I find some time, I'll do it this week, but most probably next week.

I want to fix the compability with BigWarp at the same time.

**Comment by NicoKiaru** [comment]
But I need to have a parent pom scijava with a stable version to make my builds!

It's not the case now:
https://github.com/scijava/pom-scijava/pull/254

I just test with a temp snapshot parent pom from @bogovicj 's branch, but I can't release because of that

**Comment by axtimwalde** [comment]
playground will rename its source or re-use the vistools implementation after bugs are fixed
